image:
  repository: ghcr.io/phantomsoldierking/dpin-validator-go
  tag: latest
  pullPolicy: IfNotPresent

region: us-east-1

env:
  HUB_API_URL: http://dpin-api:3001/v1
  POLL_INTERVAL_SECONDS: "5"
  HEARTBEAT_INTERVAL_SECONDS: "30"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi
